Added SensorMsgImage_CvMat.hpp/.cpp
roncapat/ros2_native_adapters pull request #2
Opened 2023-03-30 07:55 UTC by AntoBongio

NOTE:
- Check name convention
- Consider removing cv_bridge
- This implementation is constrained to the following sensor_msgs::image_encodings: {MONO8, BGR8, MONO16, BHR16, BGRA8, BGRA16}

2023-03-30 09:02 UTC, roncapat requested changes, later dismissed

2023-03-30 09:02 UTC, roncapat commented on src/SensorMsgsImage_CvMat.cpp
> +    destination.mat = cv_bridge::toCvCopy(source, source.encoding)->image;
Forse qua si può fare "move" per evitare la copia dei dati dalla `->image` alla `destination.mat`

2023-03-30 09:02 UTC, roncapat commented on src/SensorMsgsImage_CvMat.cpp
> +    destination.mat = cv_bridge::toCvCopy(source, source.encoding)->image;
cv::Mat supporta la move in teoria (https://docs.opencv.org/4.x/d3/d63/classcv_1_1Mat.html#adcaeb226bafeff8a1b262f57f6ffbcc4)

2023-03-30 16:37 UTC, AntoBongio commented on src/SensorMsgsImage_CvMat.cpp
> +    destination.mat = cv_bridge::toCvCopy(source, source.encoding)->image;
Si, potevo farla. Ho sistemato.

2023-03-31 03:56 UTC, roncapat commented
## Proposal:

### Structure names:

StampedPointCloud_PCL\
StampedImage_CV\
StampedOccupancyGrid_CV

### Headers:

SensorsMsgImage_CvMat.hpp\
NavigationOccupancyGrid_CvMat.hpp\
SensorMsgPointCloud2_PCLPointCloud.hpp

### Dummy headers:

They simply include above headers, grouped by support library used. The user should include these headers directly instead of the ones above.

CV.hpp\
PCL.hpp

2023-03-31 07:06 UTC, merged